/*==========================================================
Project : Healthcare Patient & Hospital Analytics
Database: PostgreSQL
Author  : Jainali Mehta

File:
create_tables.sql

Description:
This file creates the relational database tables required
for the Healthcare Analytics project.

Tables Created:
1. patients
2. doctors
3. appointments
4. treatments
5. billing
6. insurance_claims

Database System:
PostgreSQL
==========================================================*/

/*==========================================================
SECTION 1 : PATIENTS TABLE
Stores patient demographic and registration information.
==========================================================*/

CREATE TABLE IF NOT EXISTS patients (

    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_name VARCHAR(100) NOT NULL,

    age INTEGER,

    gender VARCHAR(20),

    city VARCHAR(50),

    province VARCHAR(50),

    registration_date DATE

);

/*==========================================================
SECTION 2 : DOCTORS TABLE
Stores healthcare provider information.
==========================================================*/

CREATE TABLE IF NOT EXISTS doctors (

    doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    doctor_name VARCHAR(100) NOT NULL,

    specialization VARCHAR(100),

    department VARCHAR(100),

    experience_years INTEGER

);

/*==========================================================
SECTION 3 : APPOINTMENTS TABLE
Stores patient appointment records.
==========================================================*/

CREATE TABLE IF NOT EXISTS appointments (

    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id INTEGER,

    doctor_id INTEGER,

    appointment_date DATE,

    appointment_status VARCHAR(50),

    visit_type VARCHAR(50),


    CONSTRAINT fk_patient

        FOREIGN KEY (patient_id)

        REFERENCES patients(patient_id),


    CONSTRAINT fk_doctor

        FOREIGN KEY (doctor_id)

        REFERENCES doctors(doctor_id)

);

/*==========================================================
SECTION 4 : TREATMENTS TABLE
Stores medical treatment details and costs.
==========================================================*/

CREATE TABLE IF NOT EXISTS treatments (

    treatment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    appointment_id INTEGER,

    treatment_name VARCHAR(100),

    treatment_category VARCHAR(100),

    treatment_cost NUMERIC(10,2),


    CONSTRAINT fk_appointment

        FOREIGN KEY (appointment_id)

        REFERENCES appointments(appointment_id)

);

/*==========================================================
SECTION 5 : BILLING TABLE
Stores healthcare billing and payment information.
==========================================================*/

CREATE TABLE IF NOT EXISTS billing (

    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id INTEGER,

    treatment_id INTEGER,

    billing_date DATE,

    total_amount NUMERIC(10,2),

    payment_status VARCHAR(50),

    payment_method VARCHAR(50),


    CONSTRAINT fk_bill_patient

        FOREIGN KEY (patient_id)

        REFERENCES patients(patient_id),


    CONSTRAINT fk_bill_treatment

        FOREIGN KEY (treatment_id)

        REFERENCES treatments(treatment_id)

);

/*==========================================================
SECTION 6 : INSURANCE CLAIMS TABLE
Stores patient insurance claim information.
==========================================================*/

CREATE TABLE IF NOT EXISTS insurance_claims (

    claim_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    patient_id INTEGER,

    insurance_provider VARCHAR(100),

    claim_amount NUMERIC(10,2),

    claim_status VARCHAR(50),

    claim_date DATE,


    CONSTRAINT fk_claim_patient

        FOREIGN KEY (patient_id)

        REFERENCES patients(patient_id)

);

/*==========================================================
End of Database Setup
==========================================================*/